/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package ocrcomparison;

import com.asprise.ocr.Ocr;
import java.awt.Image;
import java.io.File;
import java.io.FileOutputStream;
import java.net.URI;
import javax.swing.ImageIcon;
import javax.swing.JFileChooser;
import javax.swing.JOptionPane;
import javax.swing.filechooser.FileNameExtensionFilter;
import net.sourceforge.tess4j.ITesseract;
import net.sourceforge.tess4j.Tesseract;

/**
 *
 * @author JeysonGonzales
 */
public class TestOCRs extends javax.swing.JFrame {
    FileOutputStream salida;
    JFileChooser chooser = new JFileChooser();
    File file;
    Ocr instanceAs;
    Tesseract instance;
    /**
     * Creates new form TestOCRs
     */
    public TestOCRs() {
        initComponents();
        instance = new Tesseract();
        Ocr.setUp();
        instanceAs = new Ocr();
        instanceAs.startEngine("eng", Ocr.SPEED_FASTEST);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jTextField_path = new javax.swing.JTextField();
        jButton_upload = new javax.swing.JButton();
        jLabel_showImage = new javax.swing.JLabel();
        jButton_OCR = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTextArea_tess4j = new javax.swing.JTextArea();
        jLabel_exTess4j = new javax.swing.JLabel();
        jLabel_match = new javax.swing.JLabel();
        jLabel_matchAs = new javax.swing.JLabel();
        jLabel_exAsprise = new javax.swing.JLabel();
        jButton1_Guardar = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setPreferredSize(new java.awt.Dimension(810, 640));

        jButton_upload.setText("Cargar Imagen");
        jButton_upload.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton_uploadActionPerformed(evt);
            }
        });

        jButton_OCR.setText("Aplicar OCR");
        jButton_OCR.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton_OCRActionPerformed(evt);
            }
        });

        jLabel1.setText("Tesseract OCR");

        jTextArea_tess4j.setColumns(20);
        jTextArea_tess4j.setRows(5);
        jScrollPane1.setViewportView(jTextArea_tess4j);

        jButton1_Guardar.setText("Descargar");
        jButton1_Guardar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1_GuardarActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(43, 43, 43)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jButton_OCR)
                        .addContainerGap(545, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                                .addGap(101, 101, 101)
                                .addComponent(jLabel_showImage, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                            .addComponent(jLabel1, javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                                .addGap(111, 111, 111)
                                .addComponent(jLabel_exTess4j))
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                                .addGap(153, 153, 153)
                                .addComponent(jLabel_match))
                            .addComponent(jScrollPane1, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 330, Short.MAX_VALUE))
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(108, 108, 108)
                                .addComponent(jButton1_Guardar)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jLabel_matchAs, javax.swing.GroupLayout.PREFERRED_SIZE, 111, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(164, 164, 164)
                                .addComponent(jLabel_exAsprise, javax.swing.GroupLayout.PREFERRED_SIZE, 104, javax.swing.GroupLayout.PREFERRED_SIZE))))))
            .addGroup(layout.createSequentialGroup()
                .addGap(56, 56, 56)
                .addComponent(jButton_upload)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jTextField_path, javax.swing.GroupLayout.PREFERRED_SIZE, 464, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(26, 26, 26)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jTextField_path, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButton_upload))
                .addGap(9, 9, 9)
                .addComponent(jLabel_showImage, javax.swing.GroupLayout.PREFERRED_SIZE, 166, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jButton_OCR)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 211, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jLabel_exTess4j))
                    .addComponent(jLabel_exAsprise, javax.swing.GroupLayout.PREFERRED_SIZE, 12, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(jLabel_match, javax.swing.GroupLayout.Alignment.TRAILING)
                        .addComponent(jLabel_matchAs, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 12, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jButton1_Guardar))
                .addContainerGap(46, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton_uploadActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton_uploadActionPerformed
        
        //chooser.setCurrentDirectory(new File(new URI("C:/Users/JeysonGonzales/D));
        //FileNameExtensionFilter filter = new FileNameExtensionFilter("*.Images", "png");
        //chooser.addChoosableFileFilter(filter);
        chooser.showOpenDialog(null);
        file = chooser.getSelectedFile();
        String filepath = file.getAbsolutePath();
        jTextField_path.setText(filepath);
        jLabel_showImage.setIcon(ResizeImage(filepath));
    }//GEN-LAST:event_jButton_uploadActionPerformed

    private void jButton_OCRActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton_OCRActionPerformed

        try { 
            String result = instance.doOCR(file);
            result = result.replaceAll("(?m)^[ \t]*\r?\n", "");
            result = result.replaceAll("([\\n\\r]+\\s*)*$", "");
            String text=result;
            jTextArea_tess4j.setText(text);
                                
          } catch (Exception e) {
            System.err.println(e.getMessage());
        }
    }//GEN-LAST:event_jButton_OCRActionPerformed

    private void jButton1_GuardarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1_GuardarActionPerformed
        if(chooser.showDialog(null, "Guardar")==JFileChooser.APPROVE_OPTION){
            file=chooser.getSelectedFile();
            if(file.getName().endsWith("txt")){
                String Documento=jTextArea_tess4j.getText();
                String mensaje=GuardarArchivo(file,Documento);
                if(mensaje!=null){
                    JOptionPane.showMessageDialog(null, mensaje);
                }
                else{
                    JOptionPane.showMessageDialog(null, "Archivo no compatible");
                }
            }else{
               JOptionPane.showMessageDialog(null, "Guardar Documento de texto"); 
            }
        }
                  
    }//GEN-LAST:event_jButton1_GuardarActionPerformed
    public String GuardarArchivo(File archivo, String document){
        String mensaje= null;
        try{
            salida= new FileOutputStream(archivo);
            byte[]bytxt=document.getBytes();
            salida.write(bytxt);
            mensaje="archivo guardado";
        }
        catch(Exception e){
            
        }
        return mensaje;
    }
    public ImageIcon ResizeImage(String filepath) {
        ImageIcon myImage = new ImageIcon(filepath);
        Image img = myImage.getImage();
        Image newImg = img.getScaledInstance(jLabel_showImage.getWidth(), jLabel_showImage.getHeight(), Image.SCALE_SMOOTH);
        ImageIcon image = new ImageIcon(newImg);
        return image;
    }
    
        
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(TestOCRs.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(TestOCRs.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(TestOCRs.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(TestOCRs.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new TestOCRs().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1_Guardar;
    private javax.swing.JButton jButton_OCR;
    private javax.swing.JButton jButton_upload;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel_exAsprise;
    private javax.swing.JLabel jLabel_exTess4j;
    private javax.swing.JLabel jLabel_match;
    private javax.swing.JLabel jLabel_matchAs;
    private javax.swing.JLabel jLabel_showImage;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextArea jTextArea_tess4j;
    private javax.swing.JTextField jTextField_path;
    // End of variables declaration//GEN-END:variables
}
